create table if not exists personas(
    idpersona integer primary key generated by default as identity,
    nombre text not null check (nombre<>''),
    idcartilla integer references cartilla (idcartilla)
);

create table if not exists administrador(
    idadministrador integer primary key generated by default as identity,
    clave text not null check (clave<>''),
    idpersona integer references persona(idpersona)
);

create table if not exists cartillas(
    idcartilla integer primary key generated by default as identity,
    numero text not null check (numero<>''),
    codigo text not null check (codigo<>'')
);